### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by BobGu** [elguapogordo/mod_0_skills#1]
Hi @elguapogordo. I like your use of a default attribute value for the `location` of your food. I also like your use of a hash data structure for table orders, with the key being the table number, and the value being an array of what they ordered.  

- [x] I think your naming of the attribute `current_capacity` is confusing based of how some of your methods modify it.  I would expect `current_capacity` to be the number of available seats at a table.  One example that is confusing is that the `clean` method makes the `current_capacity` go to 0.  Could you rename this attribute for me or change the methods that modify this attribute to make more sense?

**Comment by elguapogordo** [comment]
you are right. the name was poorly chosen. adjusted attribute name and associated methods.
